name: Playwright Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegadores de Playwright
        run: npx playwright install

      - name: Ejecutar pruebas
        run: npx playwright test

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
